# The active animation
animation = matrix

# enable/disable big clock
bigclock = true
bigclock_12hr = true

# The character used to mask the password
asterisk = *

# Erase password input on failure
blank_password = true

# Background color id
bg = 0

# Foreground color id
fg = 8

# Blank main box background
# Setting to false will make it transparent
blank_box = true

# Remove main box borders
hide_borders = false

# Main box margins
margin_box_h = 6
margin_box_v = 3

# Input boxes length
input_len = 40

# Max input sizes
max_desktop_len = 100
max_login_len = 255
max_password_len = 255

# Remove F1/F2 command hints
hide_key_hints = true
hide_version_string = true

# limit possible login enviornments
xinitrc = null
